#!/bin/bash
set -e

echo "APP_PORT=$APP_PORT
REDIS_HOST=$REDIS_HOST
REDIS_PORT=$REDIS_PORT
REDIS_PASSWORD=$REDIS_PASSWORD
KAFKA_BROKERS=$KAFKA_BROKERS
MB_LOGIN_ID=$MB_LOGIN_ID
MB_PASSWORD=$MB_PASSWORD
MB_ACCOUNT_ID=$MB_ACCOUNT_ID
CAPTCHA_SERVICE_HOST=$CAPTCHA_SERVICE_HOST" > /app/.env

exec "$@"
